# $Id$

.include "../../share/mk/top.mk"

TEST += c89-common/2.2.1.1.c

TEST += c89-common/2.2.4.2.c

TEST += c89-common/3.2.2.2p1.c

# TODO: gcc only
CFLAGS_tests/c89-common/2.2.1.1.c += -trigraphs

